name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: LukasKalbertodt/check-basic-style@v0.1.1
      with:
        files: |
          src/**/*

  check:
    name: 'Build & test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo check
    - run: cargo test
